USE Master
GO
CREATE DATABASE DATOSOFIS
ON PRIMARY
(NAME = 'DATOSOFIS_Data',
FILENAME = 'C:\SQLData\DATOSOFIS_Data.Mdf',
SIZE = 15Mb,
MAXSIZE = 30Mb,
FILEGROWTH = 5Mb)
LOG ON
(NAME = 'DATOSOFIS_Log',
FILENAME = 'C:\SQLLog\DATOSOFIS_Log.Ldf',
SIZE = 5Mb,
MAXSIZE = 10Mb,
FILEGROWTH = 1Mb)
GO
